export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';

export const POST_LIST_BY_USER_REQUEST = 'POST_LIST_BY_USER_REQUEST';
export const POST_LIST_BY_USER_SUCCESS = 'POST_LIST_BY_USER_SUCCESS';
export const POST_LIST_BY_USER_RESET = 'POST_LIST_BY_USER_RESET';
