export const APP_STATE_INITIALIZED_YES = 'APP_STATE_INITIALIZED_YES';
export const APP_STATE_INITIALIZED_NO = 'APP_STATE_INITIALIZED_NO';

export const APP_STATE_SIDEBAR_YES = 'APP_STATE_SIDEBAR_YES';
export const APP_STATE_SIDEBAR_NO = 'APP_STATE_SIDEBAR_NO';
