export const APP_INITIALIZED_REQUEST = 'APP_INITIALIZED_REQUEST';
export const APP_INITIALIZED_SUCCESS = 'APP_INITIALIZED_SUCCESS';
export const APP_SIDEBAR_REQUEST = 'APP_SIDEBAR_REQUEST';
export const APP_SIDEBAR_SUCCESS = 'APP_SIDEBAR_SUCCESS';
